name: example

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  DEPLOY_DIR: example-dist

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: '7.x'
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:example

      - name: Deploy preview
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        run: |
          pnpm add -g netlify-cli
          netlify deploy -a=${{ env.NETLIFY_ACCESS_TOKEN }} -s=${{ env.NETLIFY_SITE_ID }} -d=${{ env.DEPLOY_DIR }} -m="$(git log -1 --pretty=%B)"
