name: publish_npm_package

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DEPLOY_DIR: example-dist

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: '7.x'
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:example

      - name: Set publish tag
        run: |
          [[ "${GITHUB_REF#refs/*/v}" =~ ^([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+)$ ]] && echo "PUBLISH_TAG=latest" >> $GITHUB_ENV || echo "PUBLISH_TAG=rc" >> $GITHUB_ENV

      - name: Deploy example
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        run: |
          pnpm add -g netlify-cli
          [[ "${PUBLISH_TAG}" == "latest" ]] && echo "PROD=true" >> $GITHUB_ENV || echo "PROD=false" >> $GITHUB_ENV
          netlify deploy -a=${{ env.NETLIFY_ACCESS_TOKEN }} -s=${{ env.NETLIFY_SITE_ID }} -d=${{ env.DEPLOY_DIR }} -m="$(git log -1 --pretty=%B) -p=${{ env.PROD }}"

      - name: Publish NPM package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${{ env.NPM_TOKEN }}"
          pnpm publish --access public --tag ${{ env.PUBLISH_TAG }}
