name: publish_npm_package

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test environment variable
        run: |
          echo ${{ env.RELEASE_VERSION }}
      # - uses: pnpm/action-setup@v2.2.2
      #   with:
      #     version: '7.x'
      #     run_install: false

      # - name: Get pnpm store directory
      #   id: pnpm-cache
      #   run: |
      #     echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      # - uses: actions/cache@v3
      #   name: Setup pnpm cache
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      # - name: Install dependencies
      #   run: pnpm install

      # - name: Build
      #   run: pnpm run build

      # - name: Publish NPM package
      #   run: pnpm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
